window.hiddenInput = document.getElementById('hidden-terminal-input');
window.displayText = document.getElementById('display-text');
window.historyContainer = document.getElementById('terminal-history');
window.scrollZone = document.getElementById('scroll-zone');
window.ambientAudio = document.getElementById('terminal-ambient');
window.splashScreen = document.getElementById('splash-screen');
window.shiftBtn = document.getElementById('start-shift-trigger');
window.terminalVideoContainer = document.getElementById('terminal-video-container');
window.viewport = document.getElementById('viewport');
window.settingsContainer = document.getElementById('settings-container');
window.settingsToggle = document.getElementById('settings-toggle-btn');
window.settingsPanel = document.getElementById('settings-panel');
window.volumeSlider = document.getElementById('volume-slider');
window.savedVolume = localStorage.getItem('ambientVolume') !== null ? parseFloat(localStorage.getItem('ambientVolume')) : 0.40;
window.leftHandImg = document.getElementById('hand-left');
window.rightHandImg = document.getElementById('hand-right');
window.stickyWrapper = document.querySelector('.sticky-note-wrapper');
window.stickyModal = document.getElementById('sticky-modal');
window.closeModal = document.getElementById('close-modal');
window.coworkerTrigger = document.getElementById('coworker-trigger');
window.taskAnomalyCompleted = localStorage.getItem('taskAnomalyCompleted') === 'true';
window.isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) || (navigator.maxTouchPoints > 0);
window.coworkerPanicCompleted = localStorage.getItem('coworkerPanicCompleted') === 'true';